sudo: false

env:
  - NODE_VERSION=4.0
  - NODE_VERSION=5.0

install:
  - nvm install $NODE_VERSION
  - npm install -g npm@^2.0.0
  - node --version
  - npm --version
  - git --version
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
  - npm install

os:
  - osx
  - linux

script:
  - grunt travis
