sudo: false

install:
  - nvm install v5.11.0
  - npm install -g npm
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
  - npm install

os:
  - osx
  - linux

script:
  - grunt travis
